### PR TITLE
Added Segment Tree

### PR DESCRIPTION
**Pull request by krishnu9**
Added implementation of segment tree with operations like range update and query.

### CODE REVIEW

**Comment by bksahu** [comment]
LGTM. I think it would be better if you move different language implementations to different directories.

**Comment by krishnu9** [comment]
How do you want the directories to be arranged? Shall I create 2 dirs inside DataStructures/ called Python/ and Cpp/ and put the files in their respective correct locations?

**Comment by bksahu** [comment]
For now, I am merging your code. If we decide to reimplement all the algorithms in different languages then we should maybe consider restructuring the directories.

**Comment by bksahu** [comment]
Just a small suggestion: Please keep your master branch always clean. Try to create new branches when sending a PR, it will save you from fixing a lot of unwanted merge conflicts in the future. :)

**Comment by krishnu9** [comment]
Sure! Will keep that in mind next time.

**Comment by krishnu9** [comment]
Hi! I need to talk to you. Would you mind sharing your contact?

**Comment by bksahu** [comment]
Sure no problem. You can reach me out at bablusahoo16@gmail.com or connect me on LinkedIn.

**Pull request merged**
